### ISSUE TITLE
整合在tomcat中报错

### ISSUE THREAD

**Issue by xander-personal** [mpusher/mpush#20]
开发环境：spring+springmvc

```
2017-09-21 17:17:38,809 INFO  [RMI TCP Connection(2)-127.0.0.1] [mpush.cache.log] - begin init redis...
2017-09-21 17:17:38,811 INFO  [RMI TCP Connection(2)-127.0.0.1] [mpush.cache.log] - init redis success...
2017-09-21 17:17:38,819 ERROR [RMI TCP Connection(2)-127.0.0.1] [org.springframework.web.servlet.DispatcherServlet] - Context initialization failed
java.lang.IllegalArgumentException: 'request' is already in use
	at io.netty.util.ConstantPool.createOrThrow(ConstantPool.java:113)
	at io.netty.util.ConstantPool.newInstance(ConstantPool.java:95)
	at io.netty.util.AttributeKey.newInstance(AttributeKey.java:55)
	at com.mpush.netty.http.NettyHttpClient.<init>(NettyHttpClient.java:64)
	at com.mpush.core.MPushServer.getHttpClient(MPushServer.java:138)
	at com.mpush.core.handler.HttpProxyHandler.<init>(HttpProxyHandler.java:61)
	at com.mpush.core.server.ConnectionServer.lambda$init$5(ConnectionServer.java:86)
	at com.mpush.common.MessageDispatcher.register(MessageDispatcher.java:68)
	at com.mpush.core.server.ConnectionServer.init(ConnectionServer.java:86)
	at com.mpush.bootstrap.job.ServerBoot.start(ServerBoot.java:44)
	at com.mpush.bootstrap.job.BootJob.startNext(BootJob.java:41)
	at com.mpush.bootstrap.job.ServiceDiscoveryBoot.start(ServiceDiscoveryBoot.java:38)
	at com.mpush.bootstrap.job.BootJob.startNext(BootJob.java:41)
	at com.mpush.bootstrap.job.ServiceRegistryBoot.start(ServiceRegistryBoot.java:36)
	at com.mpush.bootstrap.job.BootJob.startNext(BootJob.java:41)
	at com.mpush.bootstrap.job.CacheManagerBoot.start(CacheManagerBoot.java:36)
	at com.mpush.bootstrap.job.BootJob.startNext(BootJob.java:41)
	at com.mpush.bootstrap.job.BootChain$1.start(BootChain.java:44)
	at com.mpush.bootstrap.job.BootChain.start(BootChain.java:60)
	at com.mpush.bootstrap.ServerLauncher.start(ServerLauncher.java:74)
	at com.thinkgem.jeesite.common.web.MpushStartupListener.onApplicationEvent(MpushStartupListener.java:21)
	at com.thinkgem.jeesite.common.web.MpushStartupListener.onApplicationEvent(MpushStartupListener.java:13)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:98)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:333)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:335)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:778)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:485)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:658)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:624)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1183)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1099)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:989)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4931)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1702)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2017-09-21 05:17:38,866] Artifact jeesite:war exploded: Artifact is deployed successfully
[2017-09-21 05:17:38,866] Artifact jeesite:war exploded: Deploy took 25,316 milliseconds
2017-09-21 17:18:30,044 INFO  [mp-t-2-monitor] [mpush.monitor.log] - {"results":{"jvm-gc":{"fullGcCollectionCount":3,"fullGcCollectionTime":310,"spanFullGcCollectionCount":1,"spanFullGcCollectionTime":210,"spanYongGcCollectionCount":3,"spanYongGcCollectionTime":44,"yongGcCollectionCount":17,"yongGcCollectionTime":355},"jvm-info":{"freeMemory":"1062m","load":3.755859375,"maxMemory":"3641m","pid":"7217","totalMemory":"1489m"},"jvm-memory":{"edenSpaceCommitted":1282932736,"edenSpaceInit":67108864,"edenSpaceMax":1294467072,"edenSpaceUsed":372832040,"heapMemoryCommitted":1561853952,"heapMemoryInit":268435456,"heapMemoryMax":3817865216,"heapMemoryUsed":447371432,"nonHeapMemoryCommitted":112091136,"nonHeapMemoryInit":2555904,"nonHeapMemoryMax":-1,"nonHeapMemoryUsed":109055848,"oldGenCommitted":209190912,"oldGenInit":179306496,"oldGenMax":2863661056,"oldGenUsed":55924232,"permGenCommitted":0,"permGenInit":0,"permGenMax":0,"permGenUsed":0,"survivorCommitted":69730304,"survivorInit":11010048,"survivorMax":69730304,"survivorUsed":18615160},"jvm-thread":{"daemonThreadCount":58,"deadLockedThreadCount":0,"threadCount":94,"totalStartedThreadCount":122},"jvm-thread-pool":{"ack-timer":{"activeCount(workingThread)":0,"corePoolSize":1,"maxPoolSize":2147483647,"poolSize(workThread)":0,"queueSize(blockedTask)":0},"conn-worker":{"activeCount(workingThread)":16,"poolSize(workThread)":16,"queueSize(blockedTask)":0},"event-bus":{"activeCount(workingThread)":0,"corePoolSize":1,"maxPoolSize":16,"poolSize(workThread)":0,"queueSize(blockedTask)":0},"mq":{"activeCount(workingThread)":0,"corePoolSize":1,"maxPoolSize":4,"poolSize(workThread)":0,"queueSize(blockedTask)":0}}},"timestamp":1505985510041}
```

**Comment by ohun** [comment]
可能是Netty 版本有冲突

**Comment by justein** [comment]
有服务没停掉吧
