### ISSUE TITLE
RSA解密异常

### ISSUE THREAD

**Issue by raojiasong** [mpusher/mpush#44]
在网络多次连续通断的情况下，会偶发性的出现该异常，异常信息如下：
`
2019-12-17 14:03:10.231 - [mp-conn-work-3-3] ERROR - com.mpush.tools.crypto.RSAUtils - decryptByPrivateKey ex
javax.crypto.BadPaddingException: Decryption error
        at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383)
        at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294)
        at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
        at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
        at javax.crypto.Cipher.doFinal(Cipher.java:2222)
        at com.mpush.tools.crypto.RSAUtils.doFinal(RSAUtils.java:278)
        at com.mpush.tools.crypto.RSAUtils.decryptByPrivateKey(RSAUtils.java:255)
        at com.mpush.common.security.RsaCipher.decrypt(RsaCipher.java:44)
        at com.mpush.common.message.BaseMessage.decodeBinaryBody0(BaseMessage.java:90)
        at com.mpush.common.message.BaseMessage.decodeBody(BaseMessage.java:64)
        at com.mpush.common.handler.BaseMessageHandler.handle(BaseMessageHandler.java:45)
        at com.mpush.common.MessageDispatcher.onReceive(MessageDispatcher.java:86)
        at com.mpush.core.server.ServerChannelHandler.channelRead(ServerChannelHandler.java:72)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
2019-12-17 14:03:10.231 - [mp-conn-work-3-3] ERROR - com.mpush.common.MessageDispatcher - dispatch message ex, packet={cmd=5, cc=0, flags=1, sessionId=8, lrc=0, body=32}, connect=[channel=[id: 0x917a765b, L:/10.0.1.102:3000 - R:/10.0.1.253:33641], context=, status=1, lastReadTime=1576562590225, lastWriteTime=0], body=[-115, -113, -47, 23, -88, -3, -2, 35, 95, 42, -48, -109, 110, 4, -78, -47, 73, 16, 66, -35, -77, -67, 6, -103, -113, -2, 117, 78, 0, 96, 42, -23]
com.mpush.tools.crypto.CryptoException: RSA decrypt ex
        at com.mpush.tools.crypto.RSAUtils.decryptByPrivateKey(RSAUtils.java:258)
        at com.mpush.common.security.RsaCipher.decrypt(RsaCipher.java:44)
        at com.mpush.common.message.BaseMessage.decodeBinaryBody0(BaseMessage.java:90)
        at com.mpush.common.message.BaseMessage.decodeBody(BaseMessage.java:64)
        at com.mpush.common.handler.BaseMessageHandler.handle(BaseMessageHandler.java:45)
        at com.mpush.common.MessageDispatcher.onReceive(MessageDispatcher.java:86)
        at com.mpush.core.server.ServerChannelHandler.channelRead(ServerChannelHandler.java:72)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.crypto.BadPaddingException: Decryption error
        at sun.security.rsa.RSAPadding.unpadV15(RSAPadding.java:383)
        at sun.security.rsa.RSAPadding.unpad(RSAPadding.java:294)
        at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363)
        at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389)
        at javax.crypto.Cipher.doFinal(Cipher.java:2222)
        at com.mpush.tools.crypto.RSAUtils.doFinal(RSAUtils.java:278)
        at com.mpush.tools.crypto.RSAUtils.decryptByPrivateKey(RSAUtils.java:255)
        ... 24 common frames omitted
`

**Comment by ya-eternity** [comment]
我也遇到了这个问题， 请问你解决了吗？

**Comment by Fight0913** [comment]
read me


 原始邮件 
发件人: ZoeyWang<notifications@github.com>
收件人: mpusher/mpush<mpush@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2021年1月19日(周二) 17:57
主题: Re: [mpusher/mpush] RSA解密异常 (#44)


我也遇到了这个问题， 请问你解决了吗？

**Comment by raojiasong** [comment]
> 我也遇到了这个问题， 请问你解决了吗？

我解决了，是旧版本的Bug，使用最新的0.8.0版本就没这个问题了。
